consulNodeS:
  command: -server -advertise 113.132.75.250 -join 1.80.77.85
  image:  progrium/consul
  hostname: consulS
  ports:
     - "8300:8300"
     - "8301:8301"
     - "8301:8301/udp"
     - "8302:8302"
     - "8302:8302/udp"
     - "8400:8400"
     - "8500:8500"
     - "53:53/udp"
  volumes:
     - /mnt:/data
