consulNode:
	command: -server -advertise 1.80.77.85 -bootstrap-expect 2
	image:	progrium/consul
	ports:
	    - "8300:8300"
	    - "8301:8301"
	    - "8301:8301/udp"
	    - "8302:8302"
	    - "8302:8302/udp"
	    - "8400:8400"
	    - "8500:8500"
	    - "53:53/udp"
	volumes:
		- /mnt:/data
